postgres:
    image: postgres:11.10-alpine
    container_name: postgres
    restart: on-failure
    expose:
      - 5432
    command:
      - "postgres"
      - "-c"
      - "datestyle=SQL,DMY"
    environment:
      - TZ=America/Sao_Paulo
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=bolaodozeh
      - POSTGRES_HOST=postgres
    ports:
      - "5436:5432"
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d:rw